# Generated by Django 4.1.2 on 2022-10-20 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0002_remove_listing_image_name_listing_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='listing',
            old_name='author',
            new_name='user',
        ),
    ]
