# Generated by Django 4.1.2 on 2022-10-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0004_thread_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='date',
            field=models.DateField(),
        ),
    ]
