# Generated by Django 4.1.2 on 2022-10-26 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0014_notification_date_notification_thread'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='date',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='thread',
        ),
        migrations.AddField(
            model_name='thread',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
