# Generated by Django 4.1.2 on 2022-10-26 08:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('displays', '0016_rename_is_read_thread_receiver_read_thread_user_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
